name: 'CMake'
description: 'Run CMake'
inputs:
  distro:
    description: 'Distro to run on'
    required: true
    default: 'latest'
  minimal:
    description: 'If minimal'
    required: false
outputs:
  cmake:args:
    description: 'CMake args to use'
runs:
  using: 'docker'
  image: 'Dockerfile'
